#* =========  admin =========
# ! ------------ deployment ------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
  namespace: proyecto
spec:
  selector:
    matchLabels:
      app: admin
  replicas: 1
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          # image: serchiboi/proy1_api:latest
          image: alvarosp24/ayd2_admin:latest
          env:
            - name: DB_HOST
              value: "34.132.216.220"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "Pokemon*150"
            - name: DB_NAME
              value: "mydb"
            - name: DB_PORT
              value: "3306"
            - name: SERVER_PORT
              value: "4001"
            - name: CRYPTO_ALGORITHM
              value: aes-256-cbc
            - name: CRYPTO_KEY
              value: 0123456789abcdef0123456789abcdef
            - name: CRYPTO_IV
              value: 0123456789abcdef
            - name: MAIL_USER
              value: aydisco.g2@gmail.com
            - name: MAIL_PASS
              value: njojyfgvkjfijnge
            - name: JWT_SECRET
              value: analisis2junio2023
            - name: REACT_APP_CRYPTO_KEY
              value: 0123456789abcdef01234567frontend
            - name: CRYPTO_KEY_FRONTEND
              value: 0123456789abcdef01234567frontend
          ports:
            - containerPort: 4001
---
# ! ------------ Service ------------
apiVersion: v1
kind: Service
metadata:
  name: admin
  namespace: proyecto
spec:
  selector:
    app: admin
  ports:
    - name: admin
      port: 4001
      targetPort: 4001
  type: ClusterIP
  # loadBalancerIP: 35.184.184.79