#* =========  editar =========
# ! ------------ deployment ------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: editar
  namespace: proyecto
spec:
  selector:
    matchLabels:
      app: editar
  replicas: 1
  template:
    metadata:
      labels:
        app: editar
    spec:
      containers:
        - name: editar
          # image: serchiboi/proy1_api:latest
          image: alvarosp24/ayd2_editar:latest
          env:
            - name: DB_HOST
              value: "34.132.216.220"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "Pokemon*150"
            - name: DB_NAME
              value: "mydb"
            - name: DB_PORT
              value: "3306"
            - name: SERVER_PORT
              value: "3005"
            - name: AWS_ACCESS_KEY_ID
              value: "AKIAQEIHG4AZLTVCNDFQ"
            - name: AWS_SECRET_ACCESS_KEY
              value: "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"
            - name: AWS_REGION
              value: "us-east-1"
          ports:
            - containerPort: 3005
---
# ! ------------ Service ------------
apiVersion: v1
kind: Service
metadata:
  name: editar
  namespace: proyecto
spec:
  selector:
    app: editar
  ports:
    - name: editar
      port: 3005
      targetPort: 3005
  type: ClusterIP
  # loadBalancerIP: 34.27.63.95