#* =========  eliminar =========
# ! ------------ deployment ------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eliminar
  namespace: proyecto
spec:
  selector:
    matchLabels:
      app: eliminar
  replicas: 1
  template:
    metadata:
      labels:
        app: eliminar
    spec:
      containers:
        - name: eliminar
          # image: serchiboi/proy1_api:latest
          image: alvarosp24/ayd2_eliminar:latest
          env:
            - name: DB_HOST
              value: "34.132.216.220"
            - name: DB_USER
              value: "root"
            - name: DB_PASS
              value: "Pokemon*150"
            - name: DB_NAME
              value: "mydb"
            - name: DB_PORT
              value: "3306"
            - name: SERVER_PORT
              value: "3004"
            - name: AWS_ACCESS_KEY_ID
              value: "AKIAQEIHG4AZLTVCNDFQ"
            - name: AWS_SECRET_ACCESS_KEY
              value: "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"
            - name: AWS_REGION
              value: "us-east-1"
          ports:
            - containerPort: 3004
---
# ! ------------ Service ------------
apiVersion: v1
kind: Service
metadata:
  name: eliminar
  namespace: proyecto
spec:
  selector:
    app: eliminar
  ports:
    - name: eliminar
      port: 3004
      targetPort: 3004
  type: ClusterIP
  # loadBalancerIP: 130.211.222.221